name: Deploy ASP.NET Core Web Application to jobsandenvironments
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: jobsandenvironments
  AZURE_WEBAPP_PACKAGE_PATH: ./published
  AZURE_WEBAPP_PACKAGE_PATH_DOWNLOAD: webapp/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.x
  PROJECT_PATH: JobsAndEnvironments
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
  deploydev:
    needs: build
    environment:
     name: dev
     url: https://jobsandenvironments-dev.azurewebsites.net/
    runs-on: ubuntu-latest
    steps:
    - name: Update Kubernetes resources
      if: github.ref == 'refs/heads/develop' && github.event_name != 'pull_request'
      run: |
        echo "Deploy Dev"

  deploystaging:
    needs: deploydev
    environment:
     name: dev
     url: https://jobsandenvironments-staging.azurewebsites.net/
    runs-on: ubuntu-latest
    steps:
    - name: Update Kubernetes resources
      if: github.ref == 'refs/heads/staging' && github.event_name != 'pull_request'
      run: |
        echo "Deploy Staging"
      
  deployprod:
    needs: deploystaging
    environment:
     name: prod
     url: https://jobsandenvironments.azurewebsites.net/
    runs-on: ubuntu-latest
    steps:
    - name: Update Kubernetes resources
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
      run: |
        echo "Deploy Prod 1"